### ISSUE TITLE
Много лишнего в компоненте

### ISSUE THREAD

**Issue by blmzv** [JerryngtonD/AmazingHiring-test#1]
https://github.com/JerryngtonD/AmazingHiring-test/blob/545a9444f291297606149e0aa16d00af8a85b187/src/components/Table/Table.js#L15

Исходя из названия, я ожидаю в компоненте реализацию таблицы. Но вместе с этим, компонент управляет логикой отображения Loader, подготовкой данных для пагинации и прочим.

**Comment by JerryngtonD** [comment]
Да согласен, от него нужен только рендер, того, что было передано

**Comment by blmzv** [comment]
Тут даже дело не в рендере.
Простояв этом компоненте у тебя получилось много логики, которая на самом
деле должна была бы быть реализована в других компонентах.
вт, 23 окт. 2018 г. в 8:02, Jerryngton <notifications@github.com>:

**Comment by JerryngtonD** [comment]
Управление логикой вынес в отдельный компонент СontentWrapper (все изменения по ишкам залил в репу)
